import React from 'react'
import ReactDOM from 'react-dom/client'
// import App from './1.类组件和函数组件/App_class'
// import App from './1.类组件和函数组件/App_func'
// import App from './2.组件的生命周期/App'
// import App from './3.组件间的通信-父传子/App'
// import App from './4.组件间的通信-子传父/App'
// import App from './5-组件通信案例/App'
// import App from './6.组件的插槽实现/App'
// import App from './7-作用域插槽的实现/App'
// import App from './8-非父子组件通信-Context/App'
// import App from './9-非父子组件通信-EventBus/App'
// import App from './10-setState的详细使用/App'
// import App from './11-render函数的优化/App'
// import App from './12-数据不可变的力量/App'
// import App from './13-ref获取DOM和组件操作/App'
// import App from './14-受控组件和非受控组件/App'
// import App from './15-高阶组件/App'
// import App from './16-portal传送门/App'
// import App from './17-fragment/App'
// import App from './18-strictMode/App'
// import App from './19-动画实现/1-CSSTransition动画/App'
// import App from './19-动画实现/2-SwitchTransition动画/App'
import App from './19-动画实现/3-TransitionGroup动画/App'

const root = ReactDOM.createRoot(document.getElementById('root'))
root.render(<App />)
